#!/usr/bin/env python3
"""
Generates a standalone, self-contained Google Colab notebook for mBERT fine-tuning.
Includes a built-in fallback evaluator and safe TrainingArguments initialization.
"""

import json
from pathlib import Path

def create_notebook():
    notebook_path = Path(__file__).resolve().parent.parent / "notebooks" / "colab_mbert_finetuning.ipynb"

    cells = [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# 🚀 Hindi NER: mBERT Fine-Tuning (Google Colab GPU Runner)\n",
                "\n",
                "**Instructions:**\n",
                "1. Go to **Runtime > Change runtime type > Select T4 GPU**.\n",
                "2. Click **Runtime > Run all**.\n",
                "3. When finished (~12-18 mins), it will automatically download `mbert_test_metrics.json` and `mbert_predictions.json` to your Mac.\n",
                "4. Move those two downloaded files into your local `ner_using_transformers/results/` and `ner_using_transformers/results/predictions/` folders!"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Step 1: Install required libraries in Colab\n",
                "!pip install -q transformers datasets accelerate setuptools\n",
                "!pip install -q --no-deps seqeval\n",
                "\n",
                "import torch\n",
                "print(f\"CUDA Available: {torch.cuda.is_available()}\")\n",
                "if torch.cuda.is_available():\n",
                "    print(f\"Using GPU: {torch.cuda.get_device_name(0)}\")\n",
                "else:\n",
                "    print(\"⚠️ WARNING: GPU not detected! Go to Runtime > Change runtime type > Select T4 GPU for fast training.\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Step 2: Load the HiNER dataset directly via JSON files\n",
                "from datasets import load_dataset\n",
                "\n",
                "base_url = \"https://huggingface.co/datasets/cfilt/HiNER-collapsed/resolve/main/data\"\n",
                "data_files = {\n",
                "    \"train\": f\"{base_url}/train.json\",\n",
                "    \"validation\": f\"{base_url}/validation.json\",\n",
                "    \"test\": f\"{base_url}/test.json\",\n",
                "}\n",
                "\n",
                "print(\"Loading HiNER dataset...\")\n",
                "dataset = load_dataset(\"json\", data_files=data_files)\n",
                "print(\"✓ Dataset loaded:\")\n",
                "for s in dataset:\n",
                "    print(f\"  {s}: {len(dataset[s]):,} examples\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Step 3: Setup Tokenizer, Subword Alignment, and Robust Metrics\n",
                "from transformers import AutoTokenizer, AutoModelForTokenClassification, DataCollatorForTokenClassification, TrainingArguments, Trainer\n",
                "import numpy as np\n",
                "import json\n",
                "\n",
                "LABEL_LIST = [\"O\", \"B-PER\", \"I-PER\", \"B-LOC\", \"I-LOC\", \"B-ORG\", \"I-ORG\"]\n",
                "LABEL_TO_ID = {label: idx for idx, label in enumerate(LABEL_LIST)}\n",
                "ID_TO_LABEL = {idx: label for idx, label in enumerate(LABEL_LIST)}\n",
                "\n",
                "# Strict entity evaluation helper (works whether seqeval is installed or not)\n",
                "def extract_bio_entities(labels):\n",
                "    entities = []\n",
                "    curr_type = None\n",
                "    start = None\n",
                "    for i, label in enumerate(labels):\n",
                "        if label.startswith('B-'):\n",
                "            if curr_type is not None:\n",
                "                entities.append((curr_type, start, i - 1))\n",
                "            curr_type = label[2:]\n",
                "            start = i\n",
                "        elif label.startswith('I-'):\n",
                "            if curr_type is None or label[2:] != curr_type:\n",
                "                if curr_type is not None:\n",
                "                    entities.append((curr_type, start, i - 1))\n",
                "                curr_type = label[2:]\n",
                "                start = i\n",
                "        else:\n",
                "            if curr_type is not None:\n",
                "                entities.append((curr_type, start, i - 1))\n",
                "                curr_type = None\n",
                "                start = None\n",
                "    if curr_type is not None:\n",
                "        entities.append((curr_type, start, len(labels) - 1))\n",
                "    return set(entities)\n",
                "\n",
                "def compute_entity_metrics(true_seqs, pred_seqs):\n",
                "    try:\n",
                "        from seqeval.metrics import precision_score, recall_score, f1_score, classification_report\n",
                "        p = precision_score(true_seqs, pred_seqs)\n",
                "        r = recall_score(true_seqs, pred_seqs)\n",
                "        f = f1_score(true_seqs, pred_seqs)\n",
                "        rep_dict = classification_report(true_seqs, pred_seqs, output_dict=True)\n",
                "        rep_str = classification_report(true_seqs, pred_seqs)\n",
                "        return p, r, f, rep_dict, rep_str\n",
                "    except Exception:\n",
                "        # Pure Python fallback with exact same IOB2 metric math\n",
                "        tp, fp, fn = 0, 0, 0\n",
                "        by_type = {}\n",
                "        for t_seq, p_seq in zip(true_seqs, pred_seqs):\n",
                "            t_set = extract_bio_entities(t_seq)\n",
                "            p_set = extract_bio_entities(p_seq)\n",
                "            tp += len(t_set & p_set)\n",
                "            fp += len(p_set - t_set)\n",
                "            fn += len(t_set - p_set)\n",
                "            for ent_type, s, e in t_set:\n",
                "                by_type.setdefault(ent_type, {'tp': 0, 'fp': 0, 'fn': 0, 'support': 0})\n",
                "                by_type[ent_type]['support'] += 1\n",
                "                if (ent_type, s, e) in p_set:\n",
                "                    by_type[ent_type]['tp'] += 1\n",
                "                else:\n",
                "                    by_type[ent_type]['fn'] += 1\n",
                "            for ent_type, s, e in p_set:\n",
                "                by_type.setdefault(ent_type, {'tp': 0, 'fp': 0, 'fn': 0, 'support': 0})\n",
                "                if (ent_type, s, e) not in t_set:\n",
                "                    by_type[ent_type]['fp'] += 1\n",
                "        prec = tp / (tp + fp) if (tp + fp) > 0 else 0.0\n",
                "        rec = tp / (tp + fn) if (tp + fn) > 0 else 0.0\n",
                "        f1 = 2 * prec * rec / (prec + rec) if (prec + rec) > 0 else 0.0\n",
                "        rep_dict = {}\n",
                "        lines = [f\"{'':15s}{'precision':>10s}{'recall':>10s}{'f1-score':>10s}{'support':>10s}\"]\n",
                "        for ent, counts in sorted(by_type.items()):\n",
                "            ep = counts['tp'] / (counts['tp'] + counts['fp']) if (counts['tp'] + counts['fp']) > 0 else 0.0\n",
                "            er = counts['tp'] / (counts['tp'] + counts['fn']) if (counts['tp'] + counts['fn']) > 0 else 0.0\n",
                "            ef = 2 * ep * er / (ep + er) if (ep + er) > 0 else 0.0\n",
                "            rep_dict[ent] = {'precision': ep, 'recall': er, 'f1-score': ef, 'support': counts['support']}\n",
                "            lines.append(f\"{ent:15s}{ep:10.2f}{er:10.2f}{ef:10.2f}{counts['support']:10d}\")\n",
                "        rep_dict['micro avg'] = {'precision': prec, 'recall': rec, 'f1-score': f1, 'support': tp + fn}\n",
                "        lines.append(f\"\\n{'micro avg':15s}{prec:10.2f}{rec:10.2f}{f1:10.2f}{tp+fn:10d}\")\n",
                "        return prec, rec, f1, rep_dict, '\\n'.join(lines)\n",
                "\n",
                "model_name = \"bert-base-multilingual-cased\"\n",
                "tokenizer = AutoTokenizer.from_pretrained(model_name)\n",
                "\n",
                "def tokenize_and_align_labels(examples, max_length=128):\n",
                "    tokenized = tokenizer(\n",
                "        examples[\"tokens\"],\n",
                "        truncation=True,\n",
                "        max_length=max_length,\n",
                "        is_split_into_words=True,\n",
                "    )\n",
                "    all_labels = []\n",
                "    for i, labels in enumerate(examples[\"ner_tags\"]):\n",
                "        word_ids = tokenized.word_ids(batch_index=i)\n",
                "        label_ids = []\n",
                "        prev_word_idx = None\n",
                "        for word_idx in word_ids:\n",
                "            if word_idx is None:\n",
                "                label_ids.append(-100)\n",
                "            elif word_idx != prev_word_idx:\n",
                "                label_ids.append(labels[word_idx])\n",
                "            else:\n",
                "                label_ids.append(-100)\n",
                "            prev_word_idx = word_idx\n",
                "        all_labels.append(label_ids)\n",
                "    tokenized[\"labels\"] = all_labels\n",
                "    return tokenized\n",
                "\n",
                "print(\"Tokenizing dataset with label alignment...\")\n",
                "tokenized_train = dataset[\"train\"].map(tokenize_and_align_labels, batched=True)\n",
                "tokenized_val = dataset[\"validation\"].map(tokenize_and_align_labels, batched=True)\n",
                "tokenized_test = dataset[\"test\"].map(tokenize_and_align_labels, batched=True)\n",
                "print(\"✓ Tokenization complete.\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Step 4: Model Initialization & Metrics Callback\n",
                "model = AutoModelForTokenClassification.from_pretrained(\n",
                "    model_name,\n",
                "    num_labels=len(LABEL_LIST),\n",
                "    id2label=ID_TO_LABEL,\n",
                "    label2id=LABEL_TO_ID,\n",
                ")\n",
                "\n",
                "def compute_metrics(eval_preds):\n",
                "    predictions, labels = eval_preds\n",
                "    predictions = np.argmax(predictions, axis=2)\n",
                "    true_labels = []\n",
                "    pred_labels = []\n",
                "    for p_seq, l_seq in zip(predictions, labels):\n",
                "        true_s = []\n",
                "        pred_s = []\n",
                "        for p, l in zip(p_seq, l_seq):\n",
                "            if l != -100:\n",
                "                true_s.append(ID_TO_LABEL[l])\n",
                "                pred_s.append(ID_TO_LABEL[p])\n",
                "        true_labels.append(true_s)\n",
                "        pred_labels.append(pred_s)\n",
                "    p, r, f, _, _ = compute_entity_metrics(true_labels, pred_labels)\n",
                "    return {\"precision\": p, \"recall\": r, \"f1\": f}\n",
                "print(\"✓ Model and metrics initialized.\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Step 5: Fine-tune mBERT (3 Epochs with T4 GPU fp16 mixed-precision)\n",
                "# Construct training arguments safely across different transformers versions\n",
                "base_args = {\n",
                "    \"output_dir\": \"./mbert_checkpoints\",\n",
                "    \"learning_rate\": 2e-5,\n",
                "    \"per_device_train_batch_size\": 16,\n",
                "    \"per_device_eval_batch_size\": 32,\n",
                "    \"num_train_epochs\": 3,\n",
                "    \"weight_decay\": 0.01,\n",
                "    \"load_best_model_at_end\": True,\n",
                "    \"metric_for_best_model\": \"f1\",\n",
                "    \"greater_is_better\": True,\n",
                "    \"fp16\": torch.cuda.is_available(),\n",
                "    \"logging_steps\": 100,\n",
                "    \"seed\": 42,\n",
                "    \"report_to\": \"none\",\n",
                "}\n",
                "\n",
                "try:\n",
                "    training_args = TrainingArguments(eval_strategy=\"epoch\", save_strategy=\"epoch\", **base_args)\n",
                "except TypeError:\n",
                "    training_args = TrainingArguments(evaluation_strategy=\"epoch\", save_strategy=\"epoch\", **base_args)\n",
                "\n",
                "trainer = Trainer(\n",
                "    model=model,\n",
                "    args=training_args,\n",
                "    train_dataset=tokenized_train,\n",
                "    eval_dataset=tokenized_val,\n",
                "    data_collator=DataCollatorForTokenClassification(tokenizer=tokenizer),\n",
                "    compute_metrics=compute_metrics,\n",
                ")\n",
                "\n",
                "print(\"Starting training on GPU...\")\n",
                "trainer.train()"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Step 6: Evaluate on Test Set & Generate Metrics Report\n",
                "print(\"Running inference on Test split (21,657 sentences)...\")\n",
                "raw_preds = trainer.predict(tokenized_test)\n",
                "test_preds_ids = np.argmax(raw_preds.predictions, axis=2)\n",
                "\n",
                "test_true_labels = []\n",
                "test_pred_labels = []\n",
                "for p_seq, l_seq in zip(test_preds_ids, raw_preds.label_ids):\n",
                "    t_s = []\n",
                "    p_s = []\n",
                "    for p, l in zip(p_seq, l_seq):\n",
                "        if l != -100:\n",
                "            t_s.append(ID_TO_LABEL[l])\n",
                "            p_s.append(ID_TO_LABEL[p])\n",
                "    test_true_labels.append(t_s)\n",
                "    test_pred_labels.append(p_s)\n",
                "\n",
                "p, r, f, rep_dict, rep_str = compute_entity_metrics(test_true_labels, test_pred_labels)\n",
                "\n",
                "print(\"\\n\" + \"=\" * 60)\n",
                "print(\"mBERT TEST EVALUATION REPORT (Entity-Level seqeval)\")\n",
                "print(\"=\" * 60)\n",
                "print(f\"Overall Precision: {p:.4f}\")\n",
                "print(f\"Overall Recall:    {r:.4f}\")\n",
                "print(f\"Overall F1 Score:  {f:.4f}\")\n",
                "print(\"\\nDetailed Breakdown:\")\n",
                "print(rep_str)\n",
                "\n",
                "# Save metrics file\n",
                "test_metrics = {\n",
                "    \"overall_precision\": p,\n",
                "    \"overall_recall\": r,\n",
                "    \"overall_f1\": f,\n",
                "    \"report\": rep_dict,\n",
                "    \"report_str\": rep_str,\n",
                "}\n",
                "with open(\"mbert_test_metrics.json\", \"w\", encoding=\"utf-8\") as out_f:\n",
                "    json.dump(test_metrics, out_f, indent=2)\n",
                "\n",
                "# Save predictions file\n",
                "preds_list = []\n",
                "for i, ex in enumerate(dataset[\"test\"]):\n",
                "    preds_list.append({\n",
                "        \"tokens\": ex[\"tokens\"],\n",
                "        \"true_labels\": test_true_labels[i],\n",
                "        \"pred_labels\": test_pred_labels[i],\n",
                "    })\n",
                "with open(\"mbert_predictions.json\", \"w\", encoding=\"utf-8\") as out_f:\n",
                "    json.dump(preds_list, out_f, ensure_ascii=False, indent=2)\n",
                "\n",
                "print(\"\\n✓ Saved mbert_test_metrics.json and mbert_predictions.json\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Step 7: Download the resulting files to your Mac\n",
                "try:\n",
                "    from google.colab import files\n",
                "    print(\"Downloading output files to your Mac...\")\n",
                "    files.download(\"mbert_test_metrics.json\")\n",
                "    files.download(\"mbert_predictions.json\")\n",
                "    print(\"✓ Triggered browser download!\")\n",
                "except Exception as e:\n",
                "    print(\"Files are saved locally on the instance as 'mbert_test_metrics.json' and 'mbert_predictions.json'.\")\n",
                "    print(f\"Manual download note: {e}\")"
            ]
        }
    ]

    nb_json = {
        "cells": cells,
        "metadata": {
            "accelerator": "GPU",
            "colab": {"provenance": []},
            "kernelspec": {"display_name": "Python 3", "name": "python3"},
            "language_info": {"name": "python", "version": "3.10.12"}
        },
        "nbformat": 4,
        "nbformat_minor": 0
    }

    with open(notebook_path, "w", encoding="utf-8") as f:
        json.dump(nb_json, f, indent=2)

    print(f"✓ Re-generated standalone Colab notebook: {notebook_path}")

if __name__ == "__main__":
    create_notebook()
